#!/usr/bin/env python3
"""
Interactive Integration Setup Tool

This tool allows you to easily configure open-source integrations for the PBX system.
It can be run interactively or with command-line arguments.
"""

import os
import sys
import argparse
import yaml
from pathlib import Path


class IntegrationSetup:
    """Setup tool for PBX open-source integrations"""
    
    INTEGRATIONS = {
        'jitsi': {
            'name': 'Jitsi Meet',
            'description': 'Video conferencing (Free Zoom alternative)',
            'default_config': {
                'enabled': True,
                'server_url': 'https://localhost',
                'auto_create_rooms': True,
                'app_id': '',
                'app_secret': ''
            },
            'env_vars': {}
        },
        'matrix': {
            'name': 'Matrix',
            'description': 'Team messaging (Free Slack/Teams alternative)',
            'default_config': {
                'enabled': True,
                'homeserver_url': 'https://localhost:8008',
                'bot_username': '',
                'bot_password': '${MATRIX_BOT_PASSWORD}',
                'notification_room': '',
                'voicemail_room': '',
                'missed_call_notifications': True
            },
            'env_vars': {
                'MATRIX_BOT_PASSWORD': 'your-bot-password'
            }
        },
        'espocrm': {
            'name': 'EspoCRM',
            'description': 'CRM with screen pop & call logging (Free Salesforce alternative)',
            'default_config': {
                'enabled': True,
                'api_url': 'https://localhost/api/v1',
                'api_key': '${ESPOCRM_API_KEY}',
                'auto_create_contacts': True,
                'auto_log_calls': True,
                'screen_pop': True
            },
            'env_vars': {
                'ESPOCRM_API_KEY': 'your-api-key'
            }
        }
    }
    
    def __init__(self, base_path=None):
        """Initialize setup tool"""
        if base_path is None:
            # Assume script is in scripts/ directory
            self.base_path = Path(__file__).parent.parent
        else:
            self.base_path = Path(base_path)
        
        self.config_path = self.base_path / 'config.yml'
        self.env_path = self.base_path / '.env'
        self.env_example_path = self.base_path / '.env.example'
        
    def load_config(self):
        """Load current configuration"""
        if not self.config_path.exists():
            print(f"❌ Error: Config file not found at {self.config_path}")
            return None
        
        with open(self.config_path, 'r') as f:
            return yaml.safe_load(f)
    
    def save_config(self, config):
        """Save configuration to file"""
        with open(self.config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)
        print(f"✅ Configuration saved to {self.config_path}")
    
    def ensure_env_file(self):
        """Ensure .env file exists"""
        if not self.env_path.exists():
            if self.env_example_path.exists():
                # Copy from example
                with open(self.env_example_path, 'r') as src:
                    with open(self.env_path, 'w') as dst:
                        dst.write(src.read())
                print(f"✅ Created .env file from .env.example")
            else:
                # Create minimal .env
                with open(self.env_path, 'w') as f:
                    f.write("# PBX System Environment Variables\n")
                    f.write("# Auto-generated by setup_integrations.py\n\n")
                print(f"✅ Created new .env file")
    
    def update_env_file(self, key, value):
        """Update or add environment variable in .env file"""
        self.ensure_env_file()
        
        # Read existing content
        with open(self.env_path, 'r') as f:
            lines = f.readlines()
        
        # Check if key exists
        found = False
        for i, line in enumerate(lines):
            if line.strip().startswith(f"{key}="):
                lines[i] = f"{key}={value}\n"
                found = True
                break
        
        # If not found, add it
        if not found:
            lines.append(f"\n{key}={value}\n")
        
        # Write back
        with open(self.env_path, 'w') as f:
            f.writelines(lines)
        
        print(f"✅ Updated {key} in .env file")
    
    def enable_integration(self, integration_name, config_updates=None):
        """Enable an integration with optional custom configuration"""
        if integration_name not in self.INTEGRATIONS:
            print(f"❌ Error: Unknown integration '{integration_name}'")
            print(f"   Available: {', '.join(self.INTEGRATIONS.keys())}")
            return False
        
        integration = self.INTEGRATIONS[integration_name]
        print(f"\n🔧 Setting up {integration['name']}...")
        print(f"   {integration['description']}")
        
        # Load current config
        config = self.load_config()
        if config is None:
            return False
        
        # Ensure integrations section exists
        if 'integrations' not in config:
            config['integrations'] = {}
        
        # Set default configuration
        if integration_name not in config['integrations']:
            config['integrations'][integration_name] = {}
        
        # Merge with default config
        default_config = integration['default_config'].copy()
        if config_updates:
            default_config.update(config_updates)
        
        config['integrations'][integration_name].update(default_config)
        
        # Save config
        self.save_config(config)
        
        # Update environment variables
        for env_key, env_default in integration['env_vars'].items():
            if config_updates and env_key in config_updates:
                self.update_env_file(env_key, config_updates[env_key])
            else:
                # Add to .env if not exists (with default placeholder)
                self.ensure_env_file()
                with open(self.env_path, 'r') as f:
                    content = f.read()
                if env_key not in content:
                    self.update_env_file(env_key, env_default)
        
        print(f"✅ {integration['name']} integration enabled!")
        return True
    
    def disable_integration(self, integration_name):
        """Disable an integration"""
        if integration_name not in self.INTEGRATIONS:
            print(f"❌ Error: Unknown integration '{integration_name}'")
            return False
        
        integration = self.INTEGRATIONS[integration_name]
        print(f"\n🔧 Disabling {integration['name']}...")
        
        # Load current config
        config = self.load_config()
        if config is None:
            return False
        
        # Set enabled to False
        if 'integrations' in config and integration_name in config['integrations']:
            config['integrations'][integration_name]['enabled'] = False
            self.save_config(config)
            print(f"✅ {integration['name']} integration disabled!")
        else:
            print(f"ℹ️  {integration['name']} was not configured")
        
        return True
    
    def show_status(self):
        """Show status of all integrations"""
        config = self.load_config()
        if config is None:
            return
        
        print("\n📊 Integration Status")
        print("=" * 60)
        
        integrations_config = config.get('integrations', {})
        
        for int_name, int_info in self.INTEGRATIONS.items():
            status = "❌ Not configured"
            if int_name in integrations_config:
                if integrations_config[int_name].get('enabled', False):
                    status = "✅ Enabled"
                else:
                    status = "⚠️  Configured but disabled"
            
            print(f"\n{int_info['name']}")
            print(f"  Status: {status}")
            print(f"  Description: {int_info['description']}")
            
            if int_name in integrations_config:
                cfg = integrations_config[int_name]
                print(f"  Configuration:")
                for key, value in cfg.items():
                    if 'password' in key.lower() or 'secret' in key.lower() or 'key' in key.lower():
                        value_display = "***" if value else "(not set)"
                    else:
                        value_display = value if value else "(not set)"
                    print(f"    - {key}: {value_display}")
        
        print("\n" + "=" * 60)
    
    def interactive_setup(self):
        """Interactive setup wizard"""
        print("\n" + "=" * 60)
        print("🎯 PBX Integration Setup Wizard")
        print("=" * 60)
        print("\nThis wizard will help you configure open-source integrations.")
        print("All integrations are FREE and have no licensing costs!\n")
        
        # Show available integrations
        print("Available integrations:")
        for i, (int_name, int_info) in enumerate(self.INTEGRATIONS.items(), 1):
            print(f"  {i}. {int_info['name']} - {int_info['description']}")
        
        print("\nWhich integrations would you like to enable?")
        print("(Enter numbers separated by commas, or 'all' for all, or 'none' to exit)")
        
        choice = input("> ").strip().lower()
        
        if choice == 'none':
            print("Exiting setup wizard.")
            return
        
        if choice == 'all':
            selected = list(self.INTEGRATIONS.keys())
        else:
            try:
                indices = [int(x.strip()) for x in choice.split(',')]
                selected = [list(self.INTEGRATIONS.keys())[i-1] for i in indices 
                           if 1 <= i <= len(self.INTEGRATIONS)]
            except (ValueError, IndexError):
                print("❌ Invalid selection. Exiting.")
                return
        
        # Configure each selected integration
        for int_name in selected:
            self.configure_integration_interactive(int_name)
        
        print("\n" + "=" * 60)
        print("✅ Setup complete!")
        print("=" * 60)
        print("\nNext steps:")
        print("1. Review your .env file and update passwords/API keys")
        print("2. Start/restart the PBX system")
        print("3. Access the admin portal to test connections")
        print("4. See INTEGRATION_TROUBLESHOOTING_GUIDE.md for help\n")
    
    def configure_integration_interactive(self, integration_name):
        """Interactive configuration for a specific integration"""
        integration = self.INTEGRATIONS[integration_name]
        print(f"\n📝 Configuring {integration['name']}")
        print("-" * 60)
        
        config_updates = {}
        
        # Special handling for each integration
        if integration_name == 'jitsi':
            print("\nJitsi will use your local installation by default (https://localhost).")
            use_local = input("Use local server? [Y/n]: ").strip().lower()
            if use_local == 'n':
                server = input("Enter your Jitsi server URL (e.g., https://meet.jit.si): ").strip()
                config_updates['server_url'] = server
            else:
                config_updates['server_url'] = 'https://localhost'
        
        elif integration_name == 'matrix':
            print("\nMatrix will use your local Synapse installation by default (https://localhost:8008).")
            print("Matrix requires a bot account for sending notifications.")
            use_local = input("Use local Synapse server? [Y/n]: ").strip().lower()
            if use_local == 'n':
                server = input("Enter your Matrix homeserver URL (e.g., https://matrix.org): ").strip()
                config_updates['homeserver_url'] = server
            else:
                config_updates['homeserver_url'] = 'https://localhost:8008'
            
            bot_username = input("Enter bot username (e.g., @pbxbot:matrix.org): ").strip()
            if bot_username:
                config_updates['bot_username'] = bot_username
            
            print("\nℹ️  Bot password will be set in .env file (MATRIX_BOT_PASSWORD)")
            bot_password = input("Enter bot password (or press Enter to set later): ").strip()
            if bot_password:
                config_updates['MATRIX_BOT_PASSWORD'] = bot_password
        
        elif integration_name == 'espocrm':
            print("\nEspoCRM will use your local installation by default (https://localhost/api/v1).")
            use_local = input("Use local EspoCRM? [Y/n]: ").strip().lower()
            if use_local == 'n':
                api_url = input("Enter EspoCRM API URL (e.g., https://crm.yourcompany.com/api/v1): ").strip()
                if api_url:
                    config_updates['api_url'] = api_url
            else:
                config_updates['api_url'] = 'https://localhost/api/v1'
            
            print("\nℹ️  API key will be set in .env file (ESPOCRM_API_KEY)")
            api_key = input("Enter EspoCRM API key (or press Enter to set later): ").strip()
            if api_key:
                config_updates['ESPOCRM_API_KEY'] = api_key
        
        # Enable the integration
        self.enable_integration(integration_name, config_updates)


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description='Setup and configure PBX open-source integrations',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive setup wizard
  %(prog)s --interactive
  
  # Enable specific integration with defaults
  %(prog)s --enable jitsi
  %(prog)s --enable matrix
  %(prog)s --enable espocrm
  
  # Enable multiple integrations
  %(prog)s --enable jitsi,matrix,espocrm
  
  # Disable an integration
  %(prog)s --disable jitsi
  
  # Show current status
  %(prog)s --status
        """
    )
    
    parser.add_argument(
        '--interactive', '-i',
        action='store_true',
        help='Run interactive setup wizard'
    )
    
    parser.add_argument(
        '--enable', '-e',
        metavar='INTEGRATION',
        help='Enable integration(s) - comma-separated list (jitsi,matrix,espocrm)'
    )
    
    parser.add_argument(
        '--disable', '-d',
        metavar='INTEGRATION',
        help='Disable integration(s) - comma-separated list'
    )
    
    parser.add_argument(
        '--status', '-s',
        action='store_true',
        help='Show status of all integrations'
    )
    
    parser.add_argument(
        '--base-path',
        metavar='PATH',
        help='Base path to PBX installation (default: auto-detect)'
    )
    
    args = parser.parse_args()
    
    # Create setup instance
    setup = IntegrationSetup(base_path=args.base_path)
    
    # Handle commands
    if args.interactive:
        setup.interactive_setup()
    elif args.enable:
        integrations = [x.strip() for x in args.enable.split(',')]
        for integration in integrations:
            setup.enable_integration(integration)
    elif args.disable:
        integrations = [x.strip() for x in args.disable.split(',')]
        for integration in integrations:
            setup.disable_integration(integration)
    elif args.status:
        setup.show_status()
    else:
        # No arguments, show status
        setup.show_status()
        print("\nRun with --help for usage information")
        print("Run with --interactive for setup wizard")


if __name__ == '__main__':
    main()
